const products = [
  {
    _id: "1",
    name: "camille",
    image: "/images/camille.jpg",
    description: "camille",
    brand: "Plant",
    category: "Plant",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "faux watermelon",
    image: "/images/faux-watermelon.jpg",
    description: "faux watermelon",
    brand: "Plant",
    category: "Plant",
    price: 59.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: "3",
    name: "fiddle leaf",
    image: "/images/fiddle-leaf.jpg",
    description: "fiddle leaf",
    brand: "Plant",
    category: "Plant",
    price: 29.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "monstera",
    image: "/images/monstera.jpg",
    description: "monstera",
    brand: "Plant",
    category: "Plant",
    price: 39.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "palm tree",
    image: "/images/palm-tree.jpg",
    description: "palm tree",
    brand: "Plant",
    category: "Plant",
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: "6",
    name: "peace lily",
    image: "/images/peace-lily.jpg",
    description: "peace lily",
    brand: "Plant",
    category: "Plant",
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: "7",
    name: "pothos",
    image: "/images/pothos.jpg",
    description: "pothos",
    brand: "Plant",
    category: "Plant",
    price: 23.99,
    countInStock: 2,
    rating: 4.5,
    numReviews: 16,
  },
];

export default products;
